# Credit Card Fraud Detection

### Importing required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import keras 

Using TensorFlow backend.


In [2]:
cd /Users/My HP Pavilion/Desktop/data science

C:\Users\My HP Pavilion\Desktop\data science


#### Loading Data

In [3]:
data = pd.read_csv('creditcard.csv')

In [4]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

### Standardizing Data

In [5]:
from sklearn.preprocessing import StandardScaler
data['normalizedAmount'] = StandardScaler().fit_transform(data['Amount'].values.reshape(-1,1))
data = data.drop(['Amount'],axis=1)

In [6]:
targets = data['Class']

In [7]:
inputs = data.drop(['Class','Time'],axis=1)

### Spliting Data into training and testing Data

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs, targets, test_size=0.15, random_state=101)

### Spliting train data into training and validation data

In [9]:
x_train, x_validation, y_train, y_validation = train_test_split(x_train, y_train, test_size=0.15, random_state=101)

### Importing Type of Model and Layers from Keras

In [10]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

### Neural Network

In [11]:
model = Sequential()
model.add(Dense(60, input_dim=29, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(120, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(60, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

### Compiling our model

In [12]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

### Training model on 15 epochs

In [13]:
model.fit(x_train, y_train,
          batch_size=32,
          epochs=15,
          verbose=2,
          validation_data=(x_validation,y_validation))

Train on 205772 samples, validate on 36313 samples
Epoch 1/15
 - 25s - loss: 0.0188 - acc: 0.9984 - val_loss: 0.0077 - val_acc: 0.9991
Epoch 2/15
 - 22s - loss: 0.0047 - acc: 0.9992 - val_loss: 0.0053 - val_acc: 0.9991
Epoch 3/15
 - 22s - loss: 0.0042 - acc: 0.9994 - val_loss: 0.0062 - val_acc: 0.9991
Epoch 4/15
 - 24s - loss: 0.0041 - acc: 0.9994 - val_loss: 0.0082 - val_acc: 0.9991
Epoch 5/15
 - 25s - loss: 0.0040 - acc: 0.9994 - val_loss: 0.0091 - val_acc: 0.9990
Epoch 6/15
 - 25s - loss: 0.0041 - acc: 0.9994 - val_loss: 0.0065 - val_acc: 0.9991
Epoch 7/15
 - 24s - loss: 0.0041 - acc: 0.9994 - val_loss: 0.0068 - val_acc: 0.9991
Epoch 8/15
 - 24s - loss: 0.0040 - acc: 0.9994 - val_loss: 0.0061 - val_acc: 0.9992
Epoch 9/15
 - 24s - loss: 0.0038 - acc: 0.9993 - val_loss: 0.0066 - val_acc: 0.9991
Epoch 10/15
 - 24s - loss: 0.0039 - acc: 0.9994 - val_loss: 0.0070 - val_acc: 0.9991
Epoch 11/15
 - 24s - loss: 0.0037 - acc: 0.9994 - val_loss: 0.0062 - val_acc: 0.9991
Epoch 12/15
 - 24s - lo

### Testing our model of test data and printing test accuracy

In [14]:
score, acc = model.evaluate(x_test,y_test, batch_size=32,verbose=2)

print('Test accuracy', acc)

Test accuracy 0.9996020785543748


In [15]:
predict = model.predict_classes(x_test)

### Print Confusion Matrix

A confusion matrix is a summary of prediction results on a classification problem.
The number of correct and incorrect predictions are summarized with count values and broken down by each class

In [16]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predict))

[[42641     4]
 [   13    64]]


### SVM(Support-Vector Machine)

In [17]:
from sklearn.svm import SVC
svc_model=SVC()

### Training SVM

In [18]:
svc_model.fit(x_train, y_train)

C:\Users\My HP Pavilion\Anaconda3\New folder\envs\py-TF\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [19]:
y_predict_SVM=svc_model.predict(x_test)

In [20]:
print(confusion_matrix(y_test,y_predict_SVM))

[[42642     3]
 [   22    55]]


In [22]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict_SVM))

0.9994148214034924


## Decision Tree 

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
df_model = DecisionTreeClassifier(criterion = 'entropy', max_depth=15)
df_model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=15,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [25]:
Predict=df_model.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,Predict))

[[42630    15]
 [   14    63]]


In [27]:
print(accuracy_score(y_test,Predict))

0.9993211928280511


## Naive Bayes

In [28]:
from sklearn.naive_bayes import GaussianNB

In [29]:
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [30]:
predict = model.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predict))

[[41697   948]
 [    9    68]]


In [32]:
print(accuracy_score(y_test,predict))

0.977599363325687


#### Accuracy is very high for all type of models but we should make sure that emphasis of our model is on detecting fraud cases with much accuracy . So we can conclude that Neural Network and SVM are best for this case.